### Crear Usuario
POST  http://localhost:3000/register
Content-Type: application/json

{
  "nombre": "Tester Uno",
  "email": "usuario2@test.com", 
  "password": "123456"
  }

### login Usuario
POST  http://localhost:3000/login
Content-Type: application/json

{
  "email": "usuario2@test.com", 
  "password": "123456"
  }

### Crear Room
POST  http://localhost:3000/rooms
Content-Type: application/json

{
  "name": "Tester Uno"
  }

### Obtener Rooms
GET  http://localhost:3000/rooms

  